name = "tbcuk-survival"
author = "radhakr"
version = "0.3.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42847266e03daee457fc79ebeac7870637ed3a55f8f04f5df30e11a81e94e796"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"

[options]
acceptable-game-versions = ["1.18"]
