name = "tbcuk-survival"
author = "radhakr"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c92e1acb35fdbde0fa1cf0d868388ec3ee00c71b0a152a9e0c582072ad2f8a7"

[versions]
fabric = "0.12.12"
minecraft = "1.18.1"
